# Generated by Django 5.2.5 on 2025-08-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GreetingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("voice_id", models.CharField(max_length=100)),
                ("greeting_seconds", models.FloatField()),
                ("video_path", models.CharField(max_length=500)),
                ("status", models.CharField(default="queued", max_length=12)),
                ("result_url", models.URLField(blank=True, null=True)),
                ("greeting_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
